### ISSUE TITLE
Steps are in the wrong order?

### ISSUE THREAD

**Issue by jhoek** [MicrosoftDocs/dynamics365smb-devitpro-pb#372]
The steps above appear to be in the wrong order? If I understand correctly, Set-ObjectPropertiesFromMenuSuite (step 6) reads objects from the database and, after changing some properties, outputs them as text files on disk (and optionally imports the objects back into the database). Wouldn't you want these changes to be part of your delta files (which are prepared in step 5), so that they will eventually end up in your AL (when running txt2al)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfebcfad-5d9d-5365-5ae0-524780e74355
* Version Independent ID: 0a3a2ef5-ceeb-7b4d-572f-6a80a4c90c46
* Content: [The Txt2Al Conversion Tool - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-txt2al-tool)
* Content Source: [dev-itpro/developer/devenv-txt2al-tool.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-txt2al-tool.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks so much for catching this - yes, you are right, this should be run before step 5. I will update the topic asap. Thanks!

**Comment by SusanneWindfeldPedersen** [comment]
This is now fixed and will be pushed live soon. thanks.

**Comment by larswestman** [comment]
This is still wrong. Step 4 and 5 should change place so that the updated objects are imported to the modified database before exporting objects for generation of deltas
